version: '3.7'
services:

  # 有几个添加几个
  spservice1:
    image: spacemesh-service
    networks:
      - sms_network
    privileged: true
    volumes:
      # 第一个service的数据目录
      - /root/postdata1:/app/go-spacemesh/post_data
    environment:
      - THREADS=8
      - NONCES=288
      - NODE_IP=172.17.0.1
    restart: unless-stopped

  # spservice1:
  #   image: spacemesh-service
  #   networks:
  #     - sm_network
  #   privileged: true
  #   volumes:
  #     # 第2个service的数据目录
  #     - /root/postdata2:/app/go-spacemesh/post_data
  #   environment:
  #     - THREADS=8
  #     - NONCES=288
  #     - NODE_IP=172.17.0.1
  #   restart: unless-stopped
  

networks:
  sms_network:
